apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payflow.fullname" . }}
  labels:
    {{- include "payflow.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "payflow.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "payflow.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: payflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payflow.fullname" . }}-config
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payflow.fullname" . }}-config
                  key: DATABASE_PORT

            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payflow.fullname" . }}-config
                  key: DATABASE_NAME

            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payflow.fullname" . }}-config
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "payflow.fullname" . }}-secret
                  key: DATABASE_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payflow.fullname" . }}-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payflow.fullname" . }}-config
                  key: REDIS_PORT

            - name: DATABASE_URL
              value: "postgresql+psycopg://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"

            - name: REDIS_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)/0"

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
