apiVersion: v1
kind: Service
metadata:
  name: {{ include "payflow.fullname" . }}-postgres
  labels:
    {{- include "payflow.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: {{ include "payflow.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
