apiVersion: v1
kind: Service
metadata:
  name: {{ include "payflow.fullname" . }}-redis
  labels:
    {{- include "payflow.labels" . | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: {{ include "payflow.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP

